[package]
name = "mock_dex"
version = "1.0.0"
authors = ["Marco Sun <sun.dsk1@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "=4.0.0"
near-sys = "=0.2"
near-contract-standards = "=4.0.0"

